[package]
name = "pvm-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = { version = "0.3", features = ["console"] }
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
